---
abstract: 'Use subincludes in your Catalyst views'
author:
  - 'Nilson Santos Figueiredo Junior, C<< <nilsonsfj at cpan.org> >>'
build_requires:
  Catalyst::Action::RenderView: 0
  Catalyst::View::TT: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.910'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-Component-SubInclude
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Catalyst::Plugin::SubRequest: 0
  Catalyst::Runtime: 5.80014
  Moose: 0
  Moose::Role: 0
  MooseX::Types: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/catagits/Catalyst-View-Component-SubInclude
version: 0.07_03
